package com.mycompany.librarymanagment;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.imageio.ImageIO;
import javax.swing.*;

public class Login extends javax.swing.JFrame {

    public Login() {
        initComponents();
        jLabel2.requestFocus();
        jLabel2.setIcon(new ImageIcon("C:\\Users\\moasf\\Downloads\\login.png"));
        setEyeIconOpen();
        setEyeIconClosed();
        this.lblClosed.setVisible(false);
        this.lblOpen.setVisible(false);
        setText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUsername = new javax.swing.JTextField();
        lblClosed = new javax.swing.JLabel();
        lblOpen = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnSignin = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUsername.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 14)); // NOI18N
        txtUsername.setForeground(java.awt.Color.gray);
        txtUsername.setCaretColor(java.awt.Color.gray);
        txtUsername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUsernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUsernameFocusLost(evt);
            }
        });
        getContentPane().add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, 300, 50));

        lblClosed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblClosedMousePressed(evt);
            }
        });
        getContentPane().add(lblClosed, new org.netbeans.lib.awtextra.AbsoluteConstraints(705, 290, 25, 30));

        lblOpen.setBackground(new java.awt.Color(255, 255, 255));
        lblOpen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOpen.setOpaque(true);
        lblOpen.setPreferredSize(new java.awt.Dimension(40, 30));
        lblOpen.setRequestFocusEnabled(false);
        lblOpen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblOpenMousePressed(evt);
            }
        });
        getContentPane().add(lblOpen, new org.netbeans.lib.awtextra.AbsoluteConstraints(697, 290, 40, 30));

        txtPassword.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 14)); // NOI18N
        txtPassword.setForeground(java.awt.Color.gray);
        txtPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPasswordFocusLost(evt);
            }
        });
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 280, 300, 50));

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(28, 130, 148));
        jLabel1.setText("ALREADY MEMBERS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, 150, 20));

        jLabel5.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Don't have an account yet?");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 490, 210, -1));

        jLabel6.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(28, 130, 148));
        jLabel6.setText("Create an account");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel6MouseExited(evt);
            }
        });
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 520, -1, -1));

        btnSignin.setBackground(new java.awt.Color(28, 130, 148));
        btnSignin.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 20)); // NOI18N
        btnSignin.setForeground(new java.awt.Color(255, 255, 255));
        btnSignin.setText("SIGN IN");
        btnSignin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSigninActionPerformed(evt);
            }
        });
        getContentPane().add(btnSignin, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 380, 300, 50));

        jLabel2.setLabelFor(this);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSigninActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSigninActionPerformed
        String username = txtUsername.getText();
        String password = new String(txtPassword.getPassword());

        String query = "SELECT * FROM tblLogin_Details WHERE username = '" + username + "' AND password = '" + password + "'";

        ConnectionSQL con = new ConnectionSQL();
        try {
            ResultSet rs = con.executeQuery(query);
            if (rs.next()) {
                Home home = new Home();
                home.setVisible(true);
                this.dispose();
            } else {
                String message = "Invalid username or password<br>Please try again.";
                CustomDialog dialog = new CustomDialog(this, message, "Login Failed");
                dialog.setVisible(true);
            }
        } catch (SQLException e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btnSigninActionPerformed

    private void txtUsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsernameFocusGained
        if (txtUsername.getText().equals("Enter Your Username")) {
            txtUsername.setText(null);
            txtUsername.requestFocus();
            removePlaceHolderStyle(txtUsername);
        }
    }//GEN-LAST:event_txtUsernameFocusGained

    private void txtUsernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsernameFocusLost
        if (txtUsername.getText().isEmpty()) {
            addPlaceHolderStyle(txtUsername);
            txtUsername.setText("Enter Your Username");
        }

    }//GEN-LAST:event_txtUsernameFocusLost

    private void lblClosedMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblClosedMousePressed
        this.lblOpen.setVisible(true);
        this.lblClosed.setVisible(false);
        txtPassword.setEchoChar((char) 0);
    }//GEN-LAST:event_lblClosedMousePressed

    private void lblOpenMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOpenMousePressed
        this.lblClosed.setVisible(true);
        this.lblOpen.setVisible(false);
        txtPassword.setEchoChar('\u2022');
    }//GEN-LAST:event_lblOpenMousePressed

    private void txtPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFocusGained
        if (txtPassword.getText().equals("Enter Your Password")) {
            txtPassword.setText(null);
            txtPassword.requestFocus();
            removePlaceHolderStyle(txtPassword);
            txtPassword.setEchoChar('\u2022');
        }
        if (txtPassword.echoCharIsSet()) {
            this.lblClosed.setVisible(true);
            this.lblOpen.setVisible(false);
        } else {
            this.lblClosed.setVisible(false);
            this.lblOpen.setVisible(true);
        }

    }//GEN-LAST:event_txtPasswordFocusGained

    private void txtPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFocusLost
        if (txtPassword.getText().isEmpty()) {
            addPlaceHolderStyle(txtPassword);
            txtPassword.setText("Enter Your Password");
            txtPassword.setEchoChar((char) 0);
        }
        this.lblClosed.setVisible(false);
        this.lblOpen.setVisible(false);
    }//GEN-LAST:event_txtPasswordFocusLost

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void jLabel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseEntered
        jLabel6.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLabel6MouseEntered

    private void jLabel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseExited
        jLabel6.setForeground(new Color(28, 130, 148));
    }//GEN-LAST:event_jLabel6MouseExited

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        Register register = new Register();
        register.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel6MouseClicked

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSignin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private static javax.swing.JLabel lblClosed;
    private static javax.swing.JLabel lblOpen;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

    public static void addPlaceHolderStyle(JTextField textField) {
        textField.setFont(new Font("Franklin Gothic Heavy", Font.PLAIN, 14));
        textField.setForeground(Color.GRAY);
    }

    public static void removePlaceHolderStyle(JTextField textField) {
        textField.setFont(new Font("Franklin Gothic Heavy", Font.PLAIN, 16));
        textField.setForeground(Color.BLACK);
    }

    public static void setEyeIconClosed() {
        BufferedImage img = null;
        try {
            img = ImageIO.read(new File("C:\\Users\\moasf\\OneDrive\\Documents\\NetBeansProjects\\LibraryManagment\\closed.png"));
        } catch (IOException e) {
            e.printStackTrace();
        }
        Image dimg = img.getScaledInstance(lblClosed.getWidth(), lblClosed.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon imageIcon = new ImageIcon(dimg);
        lblClosed.setIcon(imageIcon);
    }

    public static void setEyeIconOpen() {
        BufferedImage img = null;
        try {
            img = ImageIO.read(new File("C:\\Users\\moasf\\OneDrive\\Documents\\NetBeansProjects\\LibraryManagment\\openey.png"));
        } catch (IOException e) {
            e.printStackTrace();
        }
        Image dimg = img.getScaledInstance(lblOpen.getWidth(), lblOpen.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon imageIcon = new ImageIcon(dimg);
        lblOpen.setIcon(imageIcon);
    }

    public void setText() {
        txtUsername.setText("Enter Your Username");
        addPlaceHolderStyle(txtUsername);
        txtPassword.setText("Enter Your Password");
        addPlaceHolderStyle(txtPassword);
        txtPassword.setEchoChar((char) 0);
    }
}
